package skill

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ChonlakanSutthimatmongkhol/repox/internal/models"
)

// Input contains the local project knowledge used to build AI instructions.
type Input struct {
	Config     models.Config
	Convention models.Convention
	Examples   []models.Example
	Lessons    []models.Lesson
}

// BuildProjectSkill renders an offline, project-specific skill for AI hosts.
func BuildProjectSkill(input Input) string {
	var b strings.Builder

	fmt.Fprintln(&b, "# Repox Project Skill")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Use this skill when working in this repository. Repox is the local source of truth for project conventions, examples, lessons, and scaffold generation.")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Safety Policy")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "- Work offline-first. Repox has no external AI provider integration.")
	fmt.Fprintln(&b, "- Use the local Repox MCP tools when available instead of guessing project structure.")
	fmt.Fprintln(&b, "- Treat `.repox/conventions.json`, `.repox/examples.json`, and `.repox/lessons.json` as local project memory.")
	fmt.Fprintln(&b, "- Ask for human review before broad refactors, template rewrites, or changes outside the requested feature.")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Required Workflow")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "1. Run or request `repox_scan` after major project structure changes.")
	fmt.Fprintln(&b, "2. Call `repox_explain_convention` before generating unfamiliar code.")
	fmt.Fprintln(&b, "3. Call `repox_find_similar` before creating a feature so existing features guide the result.")
	fmt.Fprintln(&b, "4. Use `repox_generate` for scaffold files, then edit locally to fit the task.")
	fmt.Fprintln(&b, "5. After human edits, run `repox learn` so future skill generation includes the new lessons.")
	fmt.Fprintln(&b)

	writeConventions(&b, input.Convention)
	writeExamples(&b, input.Examples)
	writeLessons(&b, input.Lessons)
	writeMCPTools(&b)

	return b.String()
}

// BuildCopilotInstructions wraps the project skill for GitHub Copilot.
func BuildCopilotInstructions(input Input) string {
	var b strings.Builder
	fmt.Fprintln(&b, "<!-- Generated by repox. Manual edits may be overwritten. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# GitHub Copilot Instructions")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Follow the Repox project skill below for this repository. Prefer local MCP tools and local project knowledge over free-form generation.")
	fmt.Fprintln(&b)
	fmt.Fprint(&b, BuildProjectSkill(input))
	return b.String()
}

func writeConventions(b *strings.Builder, conv models.Convention) {
	fmt.Fprintln(b, "## Project Conventions")
	fmt.Fprintln(b)
	fmt.Fprintf(b, "- Project type: `%s`\n", emptyDefault(conv.ProjectType, "unknown"))
	fmt.Fprintf(b, "- State management: `%s`\n", emptyDefault(conv.StateManagement, "unknown"))
	fmt.Fprintf(b, "- Feature structure: `%s`\n", emptyDefault(conv.FeatureStructure, "unknown"))
	fmt.Fprintf(b, "- Feature root: `%s`\n", emptyDefault(conv.FeatureRoot, "unknown"))
	fmt.Fprintf(b, "- Test root: `%s`\n", emptyDefault(conv.TestRoot, "unknown"))
	fmt.Fprintf(b, "- Routing: `%s` in `%s`\n", emptyDefault(conv.Routing.Type, "unknown"), emptyDefault(conv.Routing.RouteFile, "unknown"))
	fmt.Fprintln(b)

	fmt.Fprintln(b, "Naming:")
	fmt.Fprintf(b, "- Classes use `%s`\n", emptyDefault(conv.Naming.ClassCase, "unknown"))
	fmt.Fprintf(b, "- Files use `%s`\n", emptyDefault(conv.Naming.FileCase, "unknown"))
	fmt.Fprintf(b, "- Screen suffix: `%s`\n", emptyDefault(conv.Naming.ScreenSuffix, "Screen"))
	fmt.Fprintf(b, "- Bloc suffix: `%s`\n", emptyDefault(conv.Naming.BlocSuffix, "Bloc"))
	fmt.Fprintf(b, "- Event suffix: `%s`\n", emptyDefault(conv.Naming.EventSuffix, "Event"))
	fmt.Fprintf(b, "- State suffix: `%s`\n", emptyDefault(conv.Naming.StateSuffix, "State"))
	fmt.Fprintf(b, "- Repository suffix: `%s`\n", emptyDefault(conv.Naming.RepositorySuffix, "Repository"))
	fmt.Fprintf(b, "- Use case suffix: `%s`\n", emptyDefault(conv.Naming.UsecaseSuffix, "UseCase"))
	fmt.Fprintln(b)

	if len(conv.CommonImports) > 0 {
		fmt.Fprintln(b, "Common imports:")
		for _, imp := range limitStrings(conv.CommonImports, 10) {
			fmt.Fprintf(b, "- `%s`\n", imp)
		}
		fmt.Fprintln(b)
	}

	writeRoleAnatomy(b, conv.FeaturesAnalysis.RoleAnatomy)
}

func writeRoleAnatomy(b *strings.Builder, roleAnatomy map[string]models.RoleAnatomy) {
	if len(roleAnatomy) == 0 {
		return
	}
	fmt.Fprintln(b, "Role anatomy:")
	roles := make([]string, 0, len(roleAnatomy))
	for role := range roleAnatomy {
		roles = append(roles, role)
	}
	sort.Strings(roles)
	for _, role := range limitStrings(roles, 8) {
		anatomy := roleAnatomy[role]
		fmt.Fprintf(b, "- `%s` (%d files)", role, anatomy.FeatureCount)
		details := []string{}
		if len(anatomy.BaseClasses) > 0 {
			details = append(details, "base: "+anatomy.BaseClasses[0].Name)
		}
		if len(anatomy.Methods) > 0 {
			details = append(details, "methods: "+strings.Join(anatomyVoteNames(anatomy.Methods, 5), ", "))
		}
		if len(anatomy.Capabilities) > 0 {
			details = append(details, "capabilities: "+strings.Join(anatomyVoteNames(anatomy.Capabilities, 3), ", "))
		}
		if len(details) > 0 {
			fmt.Fprintf(b, " — %s", strings.Join(details, "; "))
		}
		fmt.Fprintln(b)
	}
	fmt.Fprintln(b)
}

func writeExamples(b *strings.Builder, examples []models.Example) {
	fmt.Fprintln(b, "## Existing Feature Examples")
	fmt.Fprintln(b)
	if len(examples) == 0 {
		fmt.Fprintln(b, "- No indexed examples yet. Run `repox scan` after adding representative features.")
		fmt.Fprintln(b)
		return
	}

	sort.SliceStable(examples, func(i, j int) bool {
		return examples[i].Name < examples[j].Name
	})
	for _, ex := range limitExamples(examples, 8) {
		fmt.Fprintf(b, "- `%s` at `%s`", ex.Name, ex.Path)
		components := componentsFor(ex.Metadata)
		if len(components) > 0 {
			fmt.Fprintf(b, " (%s)", strings.Join(components, ", "))
		}
		fmt.Fprintln(b)
	}
	fmt.Fprintln(b)
}

func writeLessons(b *strings.Builder, lessons []models.Lesson) {
	fmt.Fprintln(b, "## Approved Lessons")
	fmt.Fprintln(b)
	wrote := false
	for _, lesson := range lessons {
		if !lesson.Approved {
			continue
		}
		fmt.Fprintf(b, "- `%s`: %s\n", emptyDefault(lesson.Scope, "global"), lesson.Lesson)
		wrote = true
	}
	if !wrote {
		fmt.Fprintln(b, "- No approved lessons yet. Generate code, edit it, then run `repox learn`.")
	}
	fmt.Fprintln(b)
}

func writeMCPTools(b *strings.Builder) {
	fmt.Fprintln(b, "## Local MCP Tools")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "- `repox_scan`: refresh local convention and example indexes.")
	fmt.Fprintln(b, "- `repox_explain_convention`: summarize conventions before editing.")
	fmt.Fprintln(b, "- `repox_find_similar`: find local features to copy patterns from.")
	fmt.Fprintln(b, "- `repox_generate`: create deterministic scaffold files from local templates.")
	fmt.Fprintln(b, "- `repox_learn`: record lessons from reviewed developer edits.")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "Repox MCP never calls an AI provider. The AI host provides reasoning; Repox provides local project knowledge and file-safe generation.")
}

func componentsFor(meta models.FeatureMetadata) []string {
	var parts []string
	if meta.HasBloc {
		parts = append(parts, "bloc")
	}
	if meta.HasScreen {
		parts = append(parts, "screen")
	}
	if meta.HasRepository {
		parts = append(parts, "repository")
	}
	if meta.HasUseCase {
		parts = append(parts, "usecase")
	}
	if meta.HasTest {
		parts = append(parts, "test")
	}
	return parts
}

func limitExamples(examples []models.Example, max int) []models.Example {
	if len(examples) <= max {
		return examples
	}
	return examples[:max]
}

func limitStrings(values []string, max int) []string {
	if len(values) <= max {
		return values
	}
	return values[:max]
}

func anatomyVoteNames(votes []models.AnatomyVote, limit int) []string {
	if len(votes) < limit {
		limit = len(votes)
	}
	names := make([]string, 0, limit)
	for i := 0; i < limit; i++ {
		names = append(names, votes[i].Name)
	}
	return names
}

func emptyDefault(value, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}
