package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ChonlakanSutthimatmongkhol/repox/internal/config"
	"github.com/ChonlakanSutthimatmongkhol/repox/internal/models"
	projectskill "github.com/ChonlakanSutthimatmongkhol/repox/internal/skill"
)

const copilotGeneratedMarker = "<!-- Generated by repox."

var (
	skillWriteCopilot bool
	skillForce        bool
)

var skillCmd = &cobra.Command{
	Use:   "skill",
	Short: "Generate project-specific AI skill files",
}

var skillGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate offline project skill instructions from .repox knowledge",
	RunE:  runSkillGenerate,
}

func init() {
	skillGenerateCmd.Flags().BoolVar(&skillWriteCopilot, "copilot", true, "Write .github/copilot-instructions.md for Copilot Enterprise")
	skillGenerateCmd.Flags().BoolVarP(&skillForce, "force", "f", false, "Overwrite an existing human-authored Copilot instructions file")
	skillCmd.AddCommand(skillGenerateCmd)
	rootCmd.AddCommand(skillCmd)
}

func runSkillGenerate(cmd *cobra.Command, _ []string) error {
	if !config.RepoxDirExists() {
		return fmt.Errorf("no .repox/ directory found. Run `repox init` and `repox scan` first")
	}

	input, err := loadSkillInput()
	if err != nil {
		return err
	}

	skillPath := config.RepoxPath(filepath.Join("skill", "SKILL.md"))
	if err := writeTextFile(skillPath, projectskill.BuildProjectSkill(input)); err != nil {
		return fmt.Errorf("skill: write %s: %w", skillPath, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", skillPath)

	if skillWriteCopilot {
		copilotPath := filepath.Join(".github", "copilot-instructions.md")
		if err := writeCopilotInstructions(copilotPath, projectskill.BuildCopilotInstructions(input)); err != nil {
			return err
		}
		fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", copilotPath)
	}

	return nil
}

func loadSkillInput() (projectskill.Input, error) {
	cfg, err := config.Load[models.Config](config.RepoxPath("config.json"))
	if err != nil {
		return projectskill.Input{}, fmt.Errorf("skill: load config: %w", err)
	}
	conv, err := config.Load[models.Convention](config.RepoxPath("conventions.json"))
	if err != nil {
		return projectskill.Input{}, fmt.Errorf("skill: load conventions: run `repox scan` first: %w", err)
	}
	examples, _ := config.Load[[]models.Example](config.RepoxPath("examples.json"))
	lessons, _ := config.Load[[]models.Lesson](config.RepoxPath("lessons.json"))
	return projectskill.Input{
		Config:     cfg,
		Convention: conv,
		Examples:   examples,
		Lessons:    lessons,
	}, nil
}

func writeCopilotInstructions(path, content string) error {
	if existing, err := os.ReadFile(path); err == nil && !skillForce {
		if !strings.Contains(string(existing), copilotGeneratedMarker) {
			return fmt.Errorf("%s already exists and does not look generated by repox; use --force to overwrite or --copilot=false to skip", path)
		}
	}
	if err := writeTextFile(path, content); err != nil {
		return fmt.Errorf("skill: write %s: %w", path, err)
	}
	return nil
}

func writeTextFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
