package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSkillGenerate_WritesProjectSkillAndCopilotInstructions(t *testing.T) {
	dir := setupInitDir(t)
	skillWriteCopilot = true
	skillForce = false

	buf := &bytes.Buffer{}
	skillGenerateCmd.SetOut(buf)

	err := runSkillGenerate(skillGenerateCmd, nil)
	require.NoError(t, err)

	skillPath := filepath.Join(dir, ".repox", "skill", "SKILL.md")
	copilotPath := filepath.Join(dir, ".github", "copilot-instructions.md")

	skillContent, err := os.ReadFile(skillPath)
	require.NoError(t, err)
	assert.Contains(t, string(skillContent), "Repox Project Skill")
	assert.Contains(t, string(skillContent), "offline-first")
	assert.Contains(t, string(skillContent), "repox generate feature")

	copilotContent, err := os.ReadFile(copilotPath)
	require.NoError(t, err)
	assert.Contains(t, string(copilotContent), "Generated by repox")
	assert.Contains(t, string(copilotContent), "GitHub Copilot Instructions")
	assert.Contains(t, buf.String(), "wrote .repox/skill/SKILL.md")
}

func TestSkillGenerate_ProtectsHumanCopilotInstructions(t *testing.T) {
	dir := setupInitDir(t)
	skillWriteCopilot = true
	skillForce = false

	path := filepath.Join(dir, ".github", "copilot-instructions.md")
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte("human instructions"), 0o644))

	err := runSkillGenerate(skillGenerateCmd, nil)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "--force")
}

func TestSkillGenerate_CanSkipCopilotInstructions(t *testing.T) {
	dir := setupInitDir(t)
	skillWriteCopilot = false
	skillForce = false

	err := runSkillGenerate(skillGenerateCmd, nil)
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(dir, ".github", "copilot-instructions.md"))
	assert.True(t, os.IsNotExist(err))
}
